### ISSUE TITLE
Blacklist improvement

### ISSUE THREAD

**Issue by pabla** [odensc/css-loader-minify-class#2]
I think that generated classname shouldn't contains any sequences from blacklist.
For example, if I have blacklist ["ad"], then idents "ads", "boxAd", "_adfox" etc. should be rejected too.

**Comment by odensc** [comment]
Hm I'm not sure about that. Perhaps the array could take `string or RegExp`, if it's a string do a `===` check and if it's a RegExp do a `.match`.

That way if you want to match "ad" anywhere in the class, you could pass in `blacklist: [/ad/]`.

**Comment by pabla** [comment]
The solution with a RegExp would be fine too.

**Comment by odensc** [comment]
Hey @pabla, I've added something similar to the above solution (the same except it runs `.match` even if it's a string)  in dd4225fdc4fb007e686d0ebf6aa74ce99a5193a1 / `css-loader-minify-class@1.2.0`. Please let me know if that works for your use case. :)

**Comment by pabla** [comment]
If you use .match(), all strings in blacklist will be implicitly converted to RegExp, e.g. `['ad', 'ab']` -> `[/ad/, /ab/]`.
I think it's useful. Is it expected behavior?

**Comment by odensc** [comment]
Yes that's the idea. :)

**Comment by pabla** [comment]
Oh, thanks a lot!
